# -*- coding: utf-8 -*-
"""Back end Herança

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xm5bwbgcFoo5lPySi_pOORyiEWdaO3yz
"""

class Animal {
   constructor(nome, idade){
       this.nome = nome;
       this.idade = idade;
}
class Cachorro extends Animal {
    constructor(nome, idade, raca) {
        super(nome, idade);
        this.raca = raca;

        latir() {
            return ${this.nome} está latindo!
            }
        }
class Gato extends Animal {
    constructor(nome, idade, cor) {
        this.cor = cor;

        miar() {
            return '${this.nome} está miando!
            }
        }
    const meuCachorro = new Cachorro("Rex", 5, "Labrador");
    console.log(meuCachorro.descrever());
    console.log(meuCachorro.latir());

    const meuGato = new Gato("Mia", 3, "Branca");
    console.log(meuGato.decrever());
    console.log(meuGato.miar());